# Site wide configuration

title: The Purple Octopus Wiki
locale: en_US
description: How-Tos, Articles, Posts etc.
# logo: site-logo.png
logo: purple_octo.png
search: true
# host: 0.0.0.0
# url: http://srv-wiki-01:4000
# url: http://localhost:4000
url: "http://csakel.github.io/wikiblog"

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: The Golden Driver Labs
  avatar: bio-photo.jpg
  email: SystemSupport@bankofgreece.gr
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: SystemSupport
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: SystemSupport
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: SystemSupport
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
